const SENSITIVE_TITLE_WORDS = [
  "password","passwd","passphrase",
  "shared secret","secret","psk","token","api key","apikey","access key",
  "private key","certificate","cert","csr","pem","fingerprint","thumbprint",
  "radius secret","tacacs secret","key:*","confirm key"
];

function lower(s){ return String(s||"").toLowerCase(); }

function looksAutoGenerated(s) {
  if (!s) return true;
  const t = String(s).trim();
  if (!t) return true;
  if (/^x-auto-\d+/.test(t)) return true;
  if (/x-auto-\d+__/.test(t)) return true;
  if (/^css-[a-z0-9]{4,}$/i.test(t)) return true;
  if (t === "UI element" || t === "(unlabeled control)" || t === "content" || t === "Link" || t === "Button" || t === "Field") return true;
  // Big selector-y strings
  if (t.includes(">") && t.length > 20) return true;
  return false;
}

function isSensitiveTitle(s) {
  const t = lower(s);
  return SENSITIVE_TITLE_WORDS.some(w => t.includes(String(w).toLowerCase()));
}

function cleanTitle(s, fallback="(unlabeled control)") {
  if (!s) return fallback;
  let t = String(s).trim();

  // Remove "Click:" etc if present
  t = t.replace(/^\s*(click|set|change|input|navigate|nav)\s*:\s*/i, "");

  // Collapse whitespace
  t = t.replace(/\s+/g, " ").trim();

  // If it contains auto ids like x-auto-... inside
  if (/x-auto-\d+/i.test(t)) return fallback;

  // Remove trailing punctuation like ":" "*" patterns (e.g. "Key:*")
  t = t.replace(/\s*[:*]+\s*$/g, "").trim();

  if (!t) return fallback;
  if (looksAutoGenerated(t)) return fallback;
  if (isSensitiveTitle(t)) return "(sensitive field)";
  return t;
}

function titleFor(ev) {
  if (!ev) return "Step";
  const raw = ev.human || ev.label || ev.text || ev.actionKind || ev.tag || "";
  const name = cleanTitle(raw);

  if (ev.type === "click") return `${name}`;
  if (ev.type === "input") return `Type in ${name}`;
  if (ev.type === "change") {
    if (ev.checked !== null && ev.checked !== undefined) return `Set ${name} to ${ev.checked ? "ON" : "OFF"}`;
    return `Set ${name} to "${ev.value || ""}"`;
  }
  if (ev.type === "submit") return `Submit: ${name}`;
  if (ev.type === "nav") return `Navigate: ${name}`;
  if (ev.type === "outcome") return `Outcome: ${ev.outcome || ""}`;
  return cleanTitle(ev.type || "Step", "Step");
}

function el(tag, cls, text) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
}

document.addEventListener("DOMContentLoaded", async () => {
  const params = new URLSearchParams(location.search);
  const isPrint = params.get("print") === "1";
  if (isPrint) document.body.classList.add("print");

  const stored = await browser.storage.local.get(["events"]);
  const events = Array.isArray(stored.events) ? stored.events : [];
  const root = document.getElementById("steps");

  document.getElementById("meta").textContent =
    `Steps: ${events.length} | Generated: ${new Date().toLocaleString()}`;

  if (!events.length) {
    root.appendChild(el("p", null, "No steps recorded yet."));
    return;
  }

  events.forEach((ev, idx) => {
    const wrap = el("div", "step");
    wrap.appendChild(el("div", "step-title", `${idx + 1}. ${titleFor(ev)}`));
    wrap.appendChild(el("div", "step-meta", `${ev.ts || ""} — ${ev.url || ""}`));

    if (ev.screenshot) {
      const img = document.createElement("img");
      img.className = "step-img";
      img.src = ev.screenshot;
      wrap.appendChild(img);
    } else if (ev.screenshotSkipped) {
      wrap.appendChild(el("div", "step-note", `Screenshot skipped (${ev.screenshotSkipReason || "n/a"}).`));
    }
    root.appendChild(wrap);
  });

  if (isPrint) setTimeout(() => window.print(), 450);
});
